### ISSUE TITLE
Alpha Clone error

### ISSUE THREAD

**Issue by bbday** [EveHQ-Team/EveHQ#102]
I added omega then i refresh evehq Api, but ccp return expire = "",
It is possible setup or force evehq to recognize account omega instead alpha ? (also check queque skill to check if you use a omega skill then can be omega account)

**Comment by Slivo-fr** [comment]
Duplicate #1 

EveHQ cannot actually recognize omega accounts thanks to CCP choices.
There is few workaround that could work, but it's still not implemented yet. 
This issue should only affect training speed btw
