### ISSUE TITLE
[Prism] BP material calculations

### ISSUE THREAD

**Issue by Slivo-fr** [EveHQ-Team/EveHQ#52]
From following forum bug report : http://evehq.co/forum/viewtopic.php?f=5&t=101

The BP calculator does seems to round parts of the calculation, resulting in a wrong total when running batch (If I got this well)

## Notes
The thread about it is pretty big, you may take a look for examples and details about how to reproduce
The factory cost part of the thread should already be fixed

## Fixed in
2.31.6

**Comment by warlof** [comment]
After first investigation, I'm not able to reproduce the reported bug. I'll dig more this week-end and dig a bit more in the code.
