### ISSUE TITLE
[Item Browser] #System crash EveHQ

### ISSUE THREAD

**Issue by Slivo-fr** [EveHQ-Team/EveHQ#55]
From following forum bug report : http://evehq.co/forum/viewtopic.php?f=5&t=434

The #system object from SDE is available to browse and crash when browsed

## Steps to reproduce
1. Open item browser
2. browse #System->#System->#System

## Bug
The System entry should not be displayed as it's not a real item

## Expected
Filter #system out so i don't show up

## Fixed in
2.31.6

**Comment by Eshva** [comment]
It's not closed until released.
