### ISSUE TITLE
[Prism] Owner list in journal don't update

### ISSUE THREAD

**Issue by Slivo-fr** [EveHQ-Team/EveHQ#56]
From following forum bug report: http://evehq.co/forum/viewtopic.php?f=5&t=430

The owner list doesn't update at all

## Steps to reproduce
Add multiples accounts/chars/corps and remove some, I guess .. ?

## Bug
Removed chars/corps still display in the list

## Expected
List is up to date with current registered chars/corp

**Comment by Eshva** [comment]
Cannot reproduce.
