### ISSUE TITLE
[Skill planner] Advanced weapon upgrade

### ISSUE THREAD

**Issue by Slivo-fr** [EveHQ-Team/EveHQ#60]
Advanced weapon upgrade has an outdated requirement (weapon upgrade 5).
It changed a while ago and only level 4 is now required 
##Fixed in
2.31.6

**Comment by warlof** [comment]
This seems to be related to Database dump which is used to create cache.

The dgmTypeAttributes table which is containing the required skill level seems to be "corrupted" :

| TypeID | AttributeID | valueInt | valueFloat |
|---------|-------------|----------|-------------|
| 11207 | 277 | 5 | 4 |

11207 is the `typeID` for `Weapong Upgrade`
277 is the `attributeID` which specify the minimum level of the primary required skill

We can see that the attribute has for some reason two distinct value, `5` and the `4` whereas `4` should be the value for `valueInt` field.

**Comment by Slivo-fr** [comment]
Is this value exported from SDE ?

**Comment by warlof** [comment]
yes it is, from version sde-20170613 and it's the same for sde-20170712.

I've check the original YAML file provided by CCP... and it seems to be an issue at their level ^^

This is the content from `dgmTypeAttributes.yaml` available in sde-20170712
```
-   attributeID: 277
    typeID: 11207
    valueFloat: 4.0
    valueInt: 5
```

**Comment by Slivo-fr** [comment]
Here is the issue, it look like we should use the valueFloat.

**Comment by Slivo-fr** [comment]
Found the change we did again : https://github.com/EveHQ-Team/EveHQ/commit/3849527c8f74ef1690e4b8545bee1f3aaba5e319#diff-ebe5eba180217bb063e98d4b6b0571c8

Check the cachecreator.vb

**Comment by warlof** [comment]
Well, here we're in a case where two distinct value are stored for the same attribute `valueFloat` and `valueInt`.

We can't choose which of the two should be used.

One solution could be to wait a corrected SDE from CCP
Another is to alter the value inside the dump SDE using a sqlite browser like http://sqlitebrowser.org

**Comment by Slivo-fr** [comment]
Valuefloat should always been priorized over value int
That's what I learnt back then

**Comment by warlof** [comment]
hum, I figure it's dangerous to do such change but if you agree to do so, let's do it.

**Comment by Slivo-fr** [comment]
I know right, but it's some legacy sde stuff that won't change
