### ISSUE TITLE
[Fitter] Polarized weapons and T3 subsystems

### ISSUE THREAD

**Issue by Slivo-fr** [EveHQ-Team/EveHQ#62]
## Original bug report
> The way resistance calculation is done result in T3C with resist sub having some resists.
> The sub effect should be computed before the polarized effect so it's override

## Steps to reproduce
1. Open a T3C fitting (Legion).
2. Fit a subsystem that provide a bonus to resistances (ex. Legion Defensive - Augmented Plating).
3. Make sure the skill related to the step 2 sub is at least 1.
4. Add a polarized weapon to the fitting.

## Bug
The ship still have some resistance provided by the subsystem.

## Expected
The polarized weapon remove all resistances from the ship once fitted.

## Fixed in
2.31.5

**Comment by Eshva** [comment]
@Slivo-fr I don't understand what is "resist sub". Please specify it and write "Steps to reproduce" section with "Bug" and "Expected" sections as well like I done in my issues.

**Comment by Slivo-fr** [comment]
## Steps to reproduce
1. Open a T3C fitting
2. Fit a subsystem that provide a bonus to resistances
3. Make sure the skill related to the step 2 sub is at least 1
4. Add a prolarized weapon to the fitting

## Bug
The ship still have some resistance provided by the subsystem

## Expected
The polarized weapon remove all resistances from the ship once fitted
