### ISSUE TITLE
[Fitter] Contextual command "Find Module To Fit" on T3 subsystem slots spams a dialog

### ISSUE THREAD

**Issue by Slivo-fr** [EveHQ-Team/EveHQ#8]
## Steps to reproduce
1. Open EveHQ Fitter.
2. Create a new T3 Cruiser fit. For instance for Tengu.
3. In a Subsystem Slot RMC and choose the "Find Module To Fit" menu item.

## Present
A dialog with text "Subsystem Slot index must be in the range 1 to 4 for Tengu" shown 9 times. After that a correct list of subsystem present in module list. Probably the same error message shown for the same actions in any kind of T3 Cruiser slots.

## Expected
No error message is displayed and correct list of modules present.

**Comment by Eshva** [comment]
Fixed. Will be released in version 2.31.2.0
