### ISSUE TITLE
Wrong AssemblyVersion resulting in Updateloop

### ISSUE THREAD

**Issue by saulvin** [EveHQ-Team/EveHQ#82]
After updating to 2.31.7 EveHQ finds itself in an update loop.
Since the EveHQ.exe contained in 2.31.7 installer is versioned as 2.31.6

as can be seen here:
![image](https://user-images.githubusercontent.com/17982732/29611632-86b273b6-87fe-11e7-9caf-60834627fba5.png)

Both online update and a fresh install after downloading from the Website result in this behavior

regards

Saulvin

## Fixed in
2.31.7

**Comment by Eshva** [comment]
Thank you. Rebuild and reuploaded version 2.31.7. Now should be fine.
