### ISSUE TITLE
[Prism] Asset Viewer - Error exporting Assets

### ISSUE THREAD

**Issue by dstory1** [EveHQ-Team/EveHQ#90]
When exporting Asset (Full)s, receive an error stating: Error exporting Prism Asset details: Object reference not set to an instance of an object.

Exporting via the group option seems to work

## Fixed in
2.31.8

**Comment by Slivo-fr** [comment]
Hello dstory1,

Thanks for reporting !

**Comment by Eshva** [comment]
Not enough data to explore.

**Comment by Eshva** [comment]
I need at least a screen shot of your assets list and the exception log.

**Comment by dstory1** [comment]
![prism error](https://user-images.githubusercontent.com/20373339/30749852-52cb4ee0-9f7a-11e7-83f9-989168dcd6a8.PNG)

**Comment by Eshva** [comment]
The log file is located here:
```%APPDATA%\EveHQ\EveHQ.log```

**Comment by dstory1** [comment]
[EveHQ.log](https://github.com/EveHQ-Team/EveHQ/files/1325849/EveHQ.log)

**Comment by Eshva** [comment]
I've reproduced the bug. Will work on it.
