### ISSUE TITLE
[Market Prices] Market Tab not working

### ISSUE THREAD

**Issue by Slivo-fr** [EveHQ-Team/EveHQ#91]
From our forums at http://evehq.co/forum/viewtopic.php?f=5&t=465&p=1719

The market price tool previously displayed the locations of the items, it stopped working.

![image](https://user-images.githubusercontent.com/10325988/30558231-04495206-9cb1-11e7-9840-7a703c6b1e11.png)
![image](https://user-images.githubusercontent.com/10325988/30558238-09380f78-9cb1-11e7-87af-72f839e9ea38.png)

**Comment by Eshva** [comment]
Unfortunately EVE Central is down and Fuzzwork data provider doesn't supports an order list API. The only option is write a data provider for CCP's ESI API.

**Comment by Eshva** [comment]
Fixed in 2.31.11
